export default interface Contrato {
  id?: number;
  numContrato: number;
  codParc: number;
  nomeParc: string;
  nomeParcParc?: string;
  empresa?: string;
  contato?: string;
  categoriaClientes?: string;
  descricao?: string;
  natureza?: string;
  ativo: string;
  dataContrato?: string;
  localUtilizacao?: string;
  tipoContrato?: string;
  ambiente?: string;
  inscricaoEstadual?: string;
  ultimaFaturamento?: string;
  dtBase?: string;
  dtTermino?: string;
  frequencia?: number;
  diaVencimento?: number;
  vlrMensal?: number;
  vlrContrato?: number;
  parceiro?: { CODPARC: number; NOMEPARC: string; RAZAOSOCIAL?: string };
  contato_obj?: { CODCONTATO: number; NOMECONT?: string };
  empresa_obj?: { CODEMP: number; RAZAOABREV?: string; NOMEEMP?: string };
  natureza_obj?: { CODNAT: number; DESCRNAT: string };
  tipoTitulo_obj?: { CODTIPTIT: number; DESCTIPTIT?: string };
  tipoNegociacao_obj?: { CODTIPVENDA: number; DESCRTIPVENDA?: string };
  top_obj?: { CODTIPOPER: number; DESCROPER?: string };
  centroCusto_obj?: { CODCENCUS: number; DESCRCENCUS?: string };
}
